import { Footer7 } from "@/components/footer";
import type { Metadata, Viewport } from "next";

const metadata: Metadata = {
  title: "Symptom Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      {children}
      <footer className="w-full mx-auto relative">
        <Footer7 />
      </footer>
    </main>
  );
}
